### ISSUE TITLE
Suggestions for development workflow

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/ElM2D#3]
I'm trying to add a function for which I plan to submit a pull request, but I'm having some trouble with the workflow for developing. For example, I can use `pip install -e .` after cloning, or `python setup.py install`, etc. but I've been running into odd errors like the computation seeming to stall out. I was wondering what your workflow is and what you would suggest.

**Comment by sgbaird** [comment]
I think I've got a reasonable workflow in Spyder with the working directory being the directory of a local copy of a forked repository of ElM2D. If I make changes, then it seems to reflect automatically when I run a test script (see #1).

**Comment by SurgeArrester** [comment]
Typically I make my changes to the file then once it's working run `python setup.py install` to check, push to git/pip then double check it by pip installing the latest in a separate python environment, I'm not sure why the computation would stall out though sorry
